### ISSUE TITLE
Create the Presentation Slides

### ISSUE THREAD

**Issue by devarsh2395** [ThomasCalle/UTOR-PROJECT-03#43]
# Presentation Slide Soureces:
### Compatible: GoogleSlides, PowerPoint, KeyNote.
- #### infograpgia: [Website 'Click Here' Link](https://infograpia.com/?gclid=CjwKCAjwrJ-hBhB7EiwAuyBVXcg8e3pKudWZsXBdMcaqew7_fjn91D8XpTd_Eyy65v01SQvhm1VoLxoCNMsQAvD_BwE&utm_campaign=9591308532&utm_content=96198789822&utm_medium=cpc&utm_source=google&utm_term=infografia)
- #### SlidesGo: [Website 'Click Here' Link](https://slidesgo.com/)

**Comment by ThomasCalle** [comment]
Insert Links
